name: Testing

on:
  push:
    branches:
      - main

jobs:
  server_ci_pipeline:
   runs-on: ubuntu-latest

   steps:    
      - name: Adding line in readme file
        working-directory: .
        run: |
          sed -i 's#gg#pp#g' ./README.md
        shell: bash
